[package]
name = "zs-llvm"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
log = "0.4.26"
env_logger = "0.11.7"
clap = { version = "4.5.32", features = ["derive"] }
qbe = "2.4.0"
anyhow = "1.0.97"
